export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const FIND_COUNTRIES = "FIND_COUNTRIES";
export const COUNTRIES_DETAIL = "COUNTRIES_DETAIL";
export const GET_ALL_ACTIVITY = "GET_ALL_ACTIVITY";
export const FILTER_BY_CONTINENT = " FILTER_BY_CONTINENT";
export const FILTER_BY_ACTIVITY = "FILTER_BY_ACTIVITY";
export const ORDER_BY_NAME = "ORDER_BY_NAME";
export const ORDER_BY_POPULATION = "ORDER_BY_POPULATION";
